[package]
name = "suap-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cookie_store = "0.21"
directories = "6"
reqwest = { version = "0.12", default-features = false, features = ["cookies", "multipart", "rustls-tls"] }
reqwest_cookie_store = "0.8"
scraper = "0.22"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["sync", "macros", "rt-multi-thread"] }
toml = "0.8"
url = { version = "2", features = ["serde"] }

[dev-dependencies]
tempfile = "3"
wiremock = "0.6"
