[package]
name = "chamados-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "chamados"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
suap-core = { path = "../suap-core" }
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
tempfile = "3"
wiremock = "0.6"
